package com.icap.logicoti.notification;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

class WebPushDeliveryRepositoryTests {

    private JdbcTemplate jdbcTemplate;
    private WebPushDeliveryRepository repository;
    private WebPushSubscription subscription;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.h2.Driver");
        dataSource.setUrl(
                "jdbc:h2:mem:web_push_"
                        + UUID.randomUUID()
                        + ";MODE=PostgreSQL"
                        + ";DB_CLOSE_DELAY=-1"
                        + ";DATABASE_TO_LOWER=TRUE"
        );
        dataSource.setUsername("sa");
        dataSource.setPassword("");

        jdbcTemplate = new JdbcTemplate(dataSource);
        repository = new WebPushDeliveryRepository(jdbcTemplate);
        createSchema();
        seedSubscription();

        subscription = mock(WebPushSubscription.class);
        when(subscription.getId()).thenReturn(7L);
        when(subscription.getUserId()).thenReturn(3L);
    }

    @Test
    void persistsEveryAttemptAndFinalAcceptance() {
        String batchId = enqueue();
        WebPushDeliveryTarget first = repository
                .findBatch(batchId)
                .getFirst();
        Instant retryAt = Instant.now().minusSeconds(1);

        repository.recordRetryableFailure(
                first,
                503,
                "Temporal",
                retryAt,
                false,
                Instant.now()
        );

        WebPushDeliveryTarget retry = repository
                .findDue(Instant.now(), 10)
                .getFirst();

        assertThat(retry.attemptCount()).isEqualTo(1);

        repository.recordAccepted(
                retry,
                201,
                Instant.now()
        );

        assertThat(repository.countBatchByStatus(
                batchId,
                "ACCEPTED"
        )).isEqualTo(1);
        assertThat(count("web_push_delivery_attempt"))
                .isEqualTo(2);

        WebPushDeliveryResponse response = repository
                .findRecent(10, 0)
                .items()
                .getFirst();

        assertThat(response.status()).isEqualTo("ACCEPTED");
        assertThat(response.attemptCount()).isEqualTo(2);
        assertThat(response.lastHttpStatus()).isEqualTo(201);
    }

    @Test
    void closesQueuedDeliveryWhenSubscriptionBecomesInactive() {
        String batchId = enqueue();
        jdbcTemplate.update(
                "UPDATE web_push_subscription SET active = FALSE WHERE id = 7"
        );

        assertThat(
                repository.markUndeliverableSubscriptions(Instant.now())
        ).isEqualTo(1);
        assertThat(repository.countBatchByStatus(
                batchId,
                "FAILED"
        )).isEqualTo(1);
    }

    @Test
    void convertsInstantToPostgresqlSupportedUtcTimestamp() {
        Instant instant = Instant.parse("2026-08-13T19:00:00Z");

        OffsetDateTime timestamp = WebPushDeliveryRepository
                .toDatabaseTimestamp(instant);

        assertThat(timestamp).isEqualTo(
                OffsetDateTime.ofInstant(instant, ZoneOffset.UTC)
        );
        assertThat(timestamp.toInstant()).isEqualTo(instant);
        assertThat(WebPushDeliveryRepository.toDatabaseTimestamp(null))
                .isNull();
    }

    private String enqueue() {
        return repository.enqueue(
                List.of(subscription),
                "Alarma de humo",
                "Humo detectado.",
                "smoke-1",
                "/alarms",
                true
        );
    }

    private void createSchema() {
        jdbcTemplate.execute("""
                CREATE TABLE app_user (
                    id BIGINT PRIMARY KEY,
                    active BOOLEAN NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE web_push_subscription (
                    id BIGINT PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    endpoint VARCHAR(1000) NOT NULL,
                    p256dh VARCHAR(1000) NOT NULL,
                    auth VARCHAR(1000) NOT NULL,
                    active BOOLEAN NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE web_push_delivery (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    batch_id VARCHAR(36) NOT NULL,
                    subscription_id BIGINT,
                    user_id BIGINT,
                    title VARCHAR(180) NOT NULL,
                    body VARCHAR(1000) NOT NULL,
                    notification_tag VARCHAR(200) NOT NULL,
                    target_url VARCHAR(500) NOT NULL,
                    require_interaction BOOLEAN NOT NULL,
                    status VARCHAR(30) NOT NULL,
                    attempt_count INTEGER NOT NULL,
                    last_http_status INTEGER,
                    last_error VARCHAR(2000),
                    next_attempt_at TIMESTAMP WITH TIME ZONE,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    last_attempt_at TIMESTAMP WITH TIME ZONE,
                    accepted_at TIMESTAMP WITH TIME ZONE,
                    completed_at TIMESTAMP WITH TIME ZONE
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE web_push_delivery_attempt (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    delivery_id BIGINT NOT NULL,
                    attempt_number INTEGER NOT NULL,
                    outcome VARCHAR(30) NOT NULL,
                    http_status INTEGER,
                    error_message VARCHAR(2000),
                    attempted_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    UNIQUE (delivery_id, attempt_number)
                )
                """);
    }

    private void seedSubscription() {
        jdbcTemplate.update(
                "INSERT INTO app_user (id, active) VALUES (3, TRUE)"
        );
        jdbcTemplate.update("""
                INSERT INTO web_push_subscription (
                    id,
                    user_id,
                    endpoint,
                    p256dh,
                    auth,
                    active
                )
                VALUES (7, 3, ?, 'p256dh', 'auth', TRUE)
                """,
                "https://push.example/subscription"
        );
    }

    private int count(String table) {
        Integer value = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM " + table,
                Integer.class
        );
        return value == null ? 0 : value;
    }
}
