package com.icap.logicoti.alarm;

import com.icap.logicoti.exception.ConflictException;
import com.icap.logicoti.exception.ResourceNotFoundException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.messaging.simp.SimpMessagingTemplate;

import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;

class AlarmInteractionServiceTests {

    private JdbcTemplate jdbcTemplate;
    private SimpMessagingTemplate messagingTemplate;
    private AlarmInteractionService service;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource =
                new DriverManagerDataSource();

        dataSource.setDriverClassName("org.h2.Driver");
        dataSource.setUrl(
                "jdbc:h2:mem:alarm_attention_"
                        + UUID.randomUUID()
                        + ";MODE=PostgreSQL"
                        + ";DB_CLOSE_DELAY=-1"
                        + ";DATABASE_TO_LOWER=TRUE"
        );
        dataSource.setUsername("sa");
        dataSource.setPassword("");

        jdbcTemplate = new JdbcTemplate(dataSource);
        messagingTemplate = mock(SimpMessagingTemplate.class);
        service = new AlarmInteractionService(
                jdbcTemplate,
                messagingTemplate
        );

        createSchema();
        seedEvents();
    }

    @Test
    void acknowledgesAlarmAndStoresInitialComment() {
        AlarmActivityResponse response = service.acknowledge(
                10L,
                new AlarmAcknowledgeRequest(
                        "  Se notificó a seguridad.  "
                ),
                "operador"
        );

        assertThat(response.acknowledgement()).isNotNull();
        assertThat(response.acknowledgement().acknowledgedBy())
                .isEqualTo("operador");
        assertThat(response.comments())
                .extracting(AlarmCommentResponse::comment)
                .containsExactly("Se notificó a seguridad.");
        assertThat(response.commentCount()).isEqualTo(1);

        verify(messagingTemplate).convertAndSend(
                AlarmInteractionService.ATTENTION_TOPIC,
                response
        );
    }

    @Test
    void rejectsASecondAcknowledgement() {
        service.acknowledge(
                10L,
                new AlarmAcknowledgeRequest(null),
                "operador"
        );

        assertThatThrownBy(() -> service.acknowledge(
                10L,
                new AlarmAcknowledgeRequest(null),
                "admin"
        )).isInstanceOf(ConflictException.class)
                .hasMessage("Esta alarma ya fue reconocida.");
    }

    @Test
    void addsCommentsWithoutChangingAcknowledgement() {
        service.acknowledge(
                10L,
                new AlarmAcknowledgeRequest(null),
                "operador"
        );

        AlarmActivityResponse response = service.addComment(
                10L,
                new AlarmCommentRequest("Área revisada sin novedad."),
                "admin"
        );

        assertThat(response.acknowledgement().acknowledgedBy())
                .isEqualTo("operador");
        assertThat(response.comments())
                .extracting(
                        AlarmCommentResponse::comment,
                        AlarmCommentResponse::createdBy
                )
                .containsExactly(
                        org.assertj.core.groups.Tuple.tuple(
                                "Área revisada sin novedad.",
                                "admin"
                        )
                );
    }

    @Test
    void rejectsEventsThatAreNotSmokeActivations() {
        assertThatThrownBy(() -> service.findActivity(11L))
                .isInstanceOf(ResourceNotFoundException.class);

        assertThatThrownBy(() -> service.findActivity(12L))
                .isInstanceOf(ResourceNotFoundException.class);
    }

    private void createSchema() {
        jdbcTemplate.execute("""
                CREATE TABLE device_event_history (
                    id BIGINT PRIMARY KEY,
                    device_type VARCHAR(30) NOT NULL,
                    event_type VARCHAR(30) NOT NULL,
                    current_state BOOLEAN NOT NULL
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE alarm_acknowledgement (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    event_id BIGINT NOT NULL UNIQUE,
                    acknowledged_by VARCHAR(50) NOT NULL,
                    acknowledged_at TIMESTAMP WITH TIME ZONE
                        NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE alarm_comment (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    event_id BIGINT NOT NULL,
                    comment_text VARCHAR(500) NOT NULL,
                    created_by VARCHAR(50) NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE
                        NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
    }

    private void seedEvents() {
        jdbcTemplate.update(
                "INSERT INTO device_event_history VALUES "
                        + "(10, 'SMOKE', 'ACTIVATED', TRUE), "
                        + "(11, 'SMOKE', 'CLEARED', FALSE), "
                        + "(12, 'MOTION', 'ACTIVATED', TRUE)"
        );
    }
}
